import time
import threading
from collections import deque

import streamlit as st
import numpy as np
import cv2
from scipy.signal import butter, filtfilt, find_peaks

try:
    from streamlit_webrtc import webrtc_streamer, VideoProcessorBase, WebRtcMode
    from streamlit_webrtc import RTCConfiguration
    import av
    WEBRTC_AVAILABLE = True
except Exception:
    WEBRTC_AVAILABLE = False

st.set_page_config(
    page_title="PulseCare AI",
    page_icon="💗",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -------------------- Styling --------------------
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.stApp {
    background:
        radial-gradient(circle at 10% 10%, rgba(255, 105, 180, .13), transparent 28%),
        radial-gradient(circle at 90% 20%, rgba(91, 141, 239, .13), transparent 30%),
        linear-gradient(135deg, #fff7fb 0%, #f5f8ff 48%, #f7fbff 100%);
}
.hero {
    padding: 28px 30px; border-radius: 26px;
    background: linear-gradient(135deg, #ff4f81, #7c4dff);
    color: white; box-shadow: 0 15px 40px rgba(124,77,255,.20); margin-bottom: 22px;
}
.hero h1 { margin: 0; font-size: 38px; font-weight: 800; }
.hero p { margin: 8px 0 0; font-size: 15px; opacity: .94; }
.card {
    background: rgba(255,255,255,.88); border: 1px solid rgba(255,255,255,.9);
    border-radius: 22px; padding: 20px; box-shadow: 0 10px 30px rgba(42, 50, 80, .08); margin-bottom: 16px;
}
.metric-card { text-align: center; padding: 22px 12px; border-radius: 20px; background: white; box-shadow: 0 8px 25px rgba(42,50,80,.08); }
.metric-number { font-size: 36px; font-weight: 800; }
.metric-label { color: #687086; font-size: 14px; }
.status-good { background:#e9fff3; color:#087443; border-left:6px solid #16a66a; }
.status-watch { background:#fff8e7; color:#9a6500; border-left:6px solid #f2b233; }
.status-alert { background:#fff0f2; color:#a51d35; border-left:6px solid #e65068; }
.notice { padding: 14px 16px; border-radius: 14px; background: #f0f4ff; color: #394563; font-size: 14px; line-height: 1.55; }
.disclaimer { padding: 16px; border-radius: 16px; background: #fff4f6; border: 1px solid #ffd6df; color: #6e2638; font-size: 13px; line-height: 1.55; }
.ai-note { padding: 14px 16px; border-radius: 14px; background: #f4f0ff; border: 1px solid #e2d6ff; color: #3d2c66; font-size: 14px; line-height: 1.55; margin-top: 10px; }
div.stButton > button { border-radius: 14px; font-weight: 700; min-height: 46px; }
</style>
""", unsafe_allow_html=True)

# -------------------- Optional Groq (AI wellness note only — NOT used to detect vitals) --------------------
def get_ai_wellness_note(context: dict):
    """Returns a short, non-diagnostic note generated by Groq, or None if no API key is configured."""
    api_key = None
    try:
        api_key = st.secrets.get("GROQ_API_KEY")
    except Exception:
        pass
    if not api_key:
        import os
        api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return None
    try:
        from groq import Groq
        client = Groq(api_key=api_key)
        prompt = (
            "You are a cautious wellness assistant inside an educational app. "
            "Given this reading, write ONE short, friendly, non-diagnostic sentence "
            "(no medical diagnosis, no drug/dosage advice). Data: " + str(context)
        )
        resp = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=100,
            temperature=0.4,
        )
        return resp.choices[0].message.content.strip()
    except Exception:
        return None

def render_ai_note(context: dict):
    note = get_ai_wellness_note(context)
    if note:
        st.markdown(f'<div class="ai-note">🤖 <b>AI note:</b> {note}</div>', unsafe_allow_html=True)

# -------------------- Signal processing helpers --------------------
def bandpass_filter(signal, fs, low=0.7, high=3.5):
    nyq = fs / 2.0
    low_n = max(low / nyq, 0.001)
    high_n = min(high / nyq, 0.99)
    if low_n >= high_n:
        return signal
    b, a = butter(3, [low_n, high_n], btype="band")
    return filtfilt(b, a, signal)

def analyze_samples(samples, min_seconds=8):
    """samples: list of (timestamp, green_channel_mean). Handles the irregular
    frame rate of a live browser camera stream by resampling onto a uniform grid."""
    if len(samples) < 10:
        return None, 0, "Not enough data captured yet. Keep the camera steady for longer."

    ts = np.array([s[0] for s in samples], dtype=np.float64)
    vals = np.array([s[1] for s in samples], dtype=np.float64)
    duration = ts[-1] - ts[0]
    if duration < min_seconds:
        return None, 0, f"Please record at least about {min_seconds}-15 seconds."

    fs = 30.0
    uniform_t = np.arange(ts[0], ts[-1], 1.0 / fs)
    if len(uniform_t) < int(fs * min_seconds):
        return None, 0, "Recording too short or too irregular."

    signal = np.interp(uniform_t, ts, vals)
    signal -= np.mean(signal)
    if len(signal) > 7:
        kernel = np.ones(5) / 5
        signal = np.convolve(signal, kernel, mode="same")

    try:
        filtered = bandpass_filter(signal, fs)
    except Exception:
        filtered = signal

    min_distance = max(int(fs * 60 / 190), 1)
    prominence = max(np.std(filtered) * 0.25, 1e-6)
    peaks, _ = find_peaks(filtered, distance=min_distance, prominence=prominence)

    if len(peaks) < 5:
        return None, 0, "Pulse signal was too weak. Try brighter light and hold steady."

    intervals = np.diff(peaks) / fs
    intervals = intervals[(intervals > 60 / 190) & (intervals < 60 / 40)]
    if len(intervals) < 4:
        return None, 0, "A stable pulse pattern could not be detected."

    bpm_values = 60.0 / intervals
    bpm = float(np.median(bpm_values))

    cv = float(np.std(bpm_values) / max(np.mean(bpm_values), 1e-6))
    consistency = max(0.0, min(1.0, 1.0 - cv))
    duration_score = max(0.0, min(1.0, duration / 20.0))
    quality = 100 * (0.65 * consistency + 0.35 * duration_score)

    if bpm < 40 or bpm > 190:
        return None, quality, "Detected result was outside the app's reliable range. Try again."

    return bpm, quality, "Live camera-based estimate."

def heart_status(bpm):
    if bpm < 50:
        return "🧊 Low", "status-watch", "Below the common adult resting range. This can be normal for trained people, but context matters."
    if bpm <= 100:
        return "💚 Typical", "status-good", "Within the common adult resting range."
    if bpm <= 120:
        return "🟡 Elevated", "status-watch", "Above the common adult resting range. Rest and repeat the measurement."
    return "🔴 High", "status-alert", "Higher than the common adult resting range. If you feel unwell, seek medical help."

def bp_status(sys, dia):
    if sys < 90 or dia < 60:
        return "🧊 Low", "status-watch", "Blood pressure is below the usual adult reference range."
    if sys < 120 and dia < 80:
        return "💚 Typical", "status-good", "Within the usual normal adult reference range."
    if sys < 130 and dia < 80:
        return "🟡 Elevated", "status-watch", "Systolic pressure is elevated."
    if sys < 140 or dia < 90:
        return "🟠 High", "status-watch", "Above the usual normal adult reference range."
    return "🔴 High", "status-alert", "This reading is high and should be discussed with a healthcare professional, especially if repeated."

def glucose_status(value, mode):
    if mode == "Fasting":
        if value < 70:
            return "🧊 Low", "status-watch", "Below the usual fasting reference range."
        if value < 100:
            return "💚 Typical", "status-good", "Within the usual fasting reference range."
        if value < 126:
            return "🟡 Elevated", "status-watch", "Above the usual fasting reference range."
        return "🔴 High", "status-alert", "High fasting glucose should be discussed with a healthcare professional."
    else:
        if value < 70:
            return "🧊 Low", "status-watch", "Below the usual reference range."
        if value < 140:
            return "💚 Typical", "status-good", "Within a common 2-hour post-meal reference range."
        if value < 200:
            return "🟡 Elevated", "status-watch", "Higher than the usual 2-hour post-meal reference range."
        return "🔴 High", "status-alert", "High glucose should be discussed with a healthcare professional."

# -------------------- Live camera pulse processor --------------------
if WEBRTC_AVAILABLE:
    RTC_CONFIGURATION = RTCConfiguration(
        {"iceServers": [{"urls": ["stun:stun.l.google.com:19302"]}]}
    )

    class PulseProcessor(VideoProcessorBase):
        def __init__(self):
            self.lock = threading.Lock()
            self.samples = deque(maxlen=3000)
            self.recording = False

        def recv(self, frame):
            img = frame.to_ndarray(format="bgr24")
            h, w = img.shape[:2]
            y1, y2 = int(h * 0.30), int(h * 0.70)
            x1, x2 = int(w * 0.35), int(w * 0.65)
            roi = img[y1:y2, x1:x2]
            green_mean = float(np.mean(roi[:, :, 1]))

            with self.lock:
                if self.recording:
                    self.samples.append((time.time(), green_mean))

            color = (0, 210, 120) if self.recording else (255, 255, 255)
            label = "Recording..." if self.recording else "Align face / finger here"
            cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
            cv2.putText(img, label, (x1, max(y1 - 10, 15)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)
            return av.VideoFrame.from_ndarray(img, format="bgr24")

# -------------------- Header --------------------
st.markdown("""
<div class="hero">
    <h1>💗 PulseCare AI</h1>
    <p>Mobile-friendly wellness dashboard • Live camera heart rate • Blood pressure • Blood glucose</p>
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class="disclaimer">
<b>Important:</b> This is an educational wellness app, not a medical device, and it cannot diagnose
heart disease, hypertension, diabetes, or any other condition. A phone camera can estimate <b>heart rate</b>
only. It <b>cannot</b> directly measure blood pressure or blood glucose — those need a real cuff/monitor or
glucose meter, entered manually below. For urgent symptoms, contact local emergency/medical services.
</div>
""", unsafe_allow_html=True)

# -------------------- Sidebar --------------------
with st.sidebar:
    st.header("🧭 Dashboard")
    page = st.radio("Choose a tool", ["💗 Heart Rate", "🩺 Blood Pressure", "🩸 Blood Glucose", "📊 Health Summary"])
    st.divider()
    st.caption("PulseCare AI • Experimental wellness project")
    st.caption("General educational ranges — not personalized medical advice.")

# -------------------- Heart Rate (LIVE, mobile camera) --------------------
if page == "💗 Heart Rate":
    st.subheader("💗 Live Camera Pulse Estimator")

    if not WEBRTC_AVAILABLE:
        st.error("Live camera mode needs the `streamlit-webrtc` and `av` packages — make sure they're installed from requirements.txt.")
    else:
        method = st.radio(
            "Method",
            ["🙂 Face (front camera)", "☝️ Fingertip over back camera (with a light/flashlight)"],
            horizontal=False,
        )
        facing_mode = "user" if method.startswith("🙂") else "environment"

        st.markdown("""
        <div class="notice">
        Tap <b>Start</b> below, allow camera access, hold still for <b>15-20 seconds</b> under good, even light,
        then tap <b>Stop &amp; Analyze</b>. For fingertip mode, gently cover the rear camera lens with your fingertip
        near a bright light or your phone's flashlight.
        </div>
        """, unsafe_allow_html=True)

        ctx = webrtc_streamer(
            key="pulse-live",
            mode=WebRtcMode.SENDRECV,
            rtc_configuration=RTC_CONFIGURATION,
            video_processor_factory=PulseProcessor,
            media_stream_constraints={"video": {"facingMode": facing_mode}, "audio": False},
            async_processing=True,
        )

        col_a, col_b = st.columns(2)
        start_clicked = col_a.button("🔴 Start Recording", use_container_width=True)
        stop_clicked = col_b.button("⏹ Stop & Analyze", use_container_width=True)

        if ctx.video_processor:
            if start_clicked:
                with ctx.video_processor.lock:
                    ctx.video_processor.samples.clear()
                    ctx.video_processor.recording = True
                st.info("Recording... hold steady for 15-20 seconds, then tap Stop & Analyze.")

            if stop_clicked:
                with ctx.video_processor.lock:
                    ctx.video_processor.recording = False
                    samples = list(ctx.video_processor.samples)

                bpm, quality, msg = analyze_samples(samples)
                if bpm is None:
                    st.error("⚠️ " + msg)
                    st.info("Try again with brighter, even lighting and a steadier hold.")
                else:
                    status, css, explanation = heart_status(bpm)
                    c1, c2, c3 = st.columns(3)
                    with c1:
                        st.markdown(f'<div class="metric-card"><div class="metric-number">💓 {bpm:.0f}</div><div class="metric-label">Estimated BPM</div></div>', unsafe_allow_html=True)
                    with c2:
                        st.markdown(f'<div class="metric-card"><div class="metric-number">📈 {quality:.0f}%</div><div class="metric-label">Signal quality</div></div>', unsafe_allow_html=True)
                    with c3:
                        st.markdown(f'<div class="metric-card"><div class="metric-number">🧠 {status}</div><div class="metric-label">Wellness interpretation</div></div>', unsafe_allow_html=True)
                    st.markdown(f'<div class="card {css}"><b>{status}</b><br>{explanation}</div>', unsafe_allow_html=True)
                    render_ai_note({"type": "heart_rate", "bpm": round(bpm), "status": status})
        else:
            st.caption("Waiting for camera connection... on mobile, tap the camera prompt to allow access.")

    st.divider()
    st.subheader("📌 Better measurement tips")
    for t in [
        "Keep the phone/camera steady and avoid moving.",
        "Use good, even lighting (or your flashlight for fingertip mode).",
        "Record for 15-20 seconds for a stable reading.",
        "Do not use the result for emergency decisions.",
        "Compare repeated readings only under similar resting conditions.",
    ]:
        st.write("• " + t)

# -------------------- Blood Pressure --------------------
elif page == "🩺 Blood Pressure":
    st.subheader("🩺 Blood Pressure Check")
    st.markdown("""
    <div class="notice">
    A smartphone camera cannot reliably measure blood pressure — it needs an actual cuff/monitor.
    Enter your reading below for an educational interpretation.
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        systolic = st.number_input("Systolic (upper) mmHg", min_value=50, max_value=250, value=120, step=1)
    with col2:
        diastolic = st.number_input("Diastolic (lower) mmHg", min_value=30, max_value=160, value=80, step=1)

    if st.button("🩺 Check Blood Pressure", use_container_width=True):
        status, css, explanation = bp_status(systolic, diastolic)
        st.markdown(f"""
        <div class="card {css}">
            <h2 style="margin-top:0">🩺 {systolic:.0f}/{diastolic:.0f} mmHg</h2>
            <b>{status}</b><br>{explanation}
        </div>
        """, unsafe_allow_html=True)
        render_ai_note({"type": "blood_pressure", "systolic": systolic, "diastolic": diastolic, "status": status})

    st.info("If a reading is repeatedly unusual, discuss it with a qualified healthcare professional.")

# -------------------- Blood Glucose --------------------
elif page == "🩸 Blood Glucose":
    st.subheader("🩸 Blood Glucose Check")
    st.markdown("""
    <div class="notice">
    A smartphone cannot directly measure blood glucose. Enter a reading from a glucose meter/approved
    sensor for an educational interpretation.
    </div>
    """, unsafe_allow_html=True)

    mode = st.selectbox("Reading type", ["Fasting", "2-hour post-meal"])
    unit = st.radio("Unit", ["mg/dL", "mmol/L"], horizontal=True)

    if unit == "mg/dL":
        value = st.number_input("Glucose value", min_value=20.0, max_value=700.0, value=90.0, step=1.0)
        mgdl = value
    else:
        value = st.number_input("Glucose value", min_value=1.0, max_value=40.0, value=5.0, step=0.1)
        mgdl = value * 18.0182

    if st.button("🩸 Check Glucose", use_container_width=True):
        status, css, explanation = glucose_status(mgdl, mode)
        st.markdown(f"""
        <div class="card {css}">
            <h2 style="margin-top:0">🩸 {value:.1f} {unit}</h2>
            <b>{status}</b><br>{explanation}
        </div>
        """, unsafe_allow_html=True)
        render_ai_note({"type": "glucose", "value": value, "unit": unit, "mode": mode, "status": status})

    st.info("Glucose targets can vary by person and medical situation. Use your clinician's targets when available.")

# -------------------- Summary --------------------
else:
    st.subheader("📊 Health Summary")
    st.markdown("""
    <div class="card">
        <h3>✨ Your wellness snapshot</h3>
        <p>PulseCare AI separates what a phone camera can genuinely estimate (heart rate) from readings
        that require real medical devices (blood pressure, glucose).</p>
    </div>
    """, unsafe_allow_html=True)

    st.write("### 🧠 What each feature can actually measure")
    for icon, feature, note in [
        ("💗 Heart rate", "Live camera estimate (face or fingertip)", "Experimental, not medical-grade"),
        ("🩺 Blood pressure", "Reading entered from a BP cuff/monitor", "Phone alone cannot measure this"),
        ("🩸 Blood glucose", "Reading entered from a glucose meter/sensor", "Phone alone cannot measure this"),
    ]:
        st.markdown(f'<div class="card"><h4>{icon} {feature}</h4><p>{note}</p></div>', unsafe_allow_html=True)

st.divider()
st.caption("💗 PulseCare AI is for educational wellness use only. It does not replace professional medical advice or validated medical devices.")
