import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(
    page_title="PulseCare AI",
    page_icon="💗",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -------------------- Styling --------------------
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
:root, html, body { color-scheme: light only; }
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.stApp {
    background:
        radial-gradient(circle at 10% 10%, rgba(255, 105, 180, .13), transparent 28%),
        radial-gradient(circle at 90% 20%, rgba(91, 141, 239, .13), transparent 30%),
        linear-gradient(135deg, #fff7fb 0%, #f5f8ff 48%, #f7fbff 100%);
}
.hero {
    padding: 28px 30px; border-radius: 26px;
    background: linear-gradient(135deg, #ff4f81, #7c4dff);
    color: white; box-shadow: 0 15px 40px rgba(124,77,255,.20); margin-bottom: 22px;
}
.hero h1 { margin: 0; font-size: 38px; font-weight: 800; }
.hero p { margin: 8px 0 0; font-size: 15px; opacity: .94; }
.card {
    background: rgba(255,255,255,.88); border: 1px solid rgba(255,255,255,.9);
    border-radius: 22px; padding: 20px; box-shadow: 0 10px 30px rgba(42, 50, 80, .08); margin-bottom: 16px;
    color: #23293a;
}
.card h1, .card h2, .card h3, .card h4, .card h5, .card p, .card b, .card span, .card div {
    color: inherit;
}
.metric-card {
    text-align: center; padding: 22px 12px; border-radius: 20px; background: white;
    box-shadow: 0 8px 25px rgba(42,50,80,.08); color: #23293a;
}
.metric-card .metric-number { color: #23293a; }
.metric-number { font-size: 36px; font-weight: 800; }
.metric-label { color: #687086; font-size: 14px; }
.status-good { background:#e9fff3; color:#087443; border-left:6px solid #16a66a; }
.status-watch { background:#fff8e7; color:#9a6500; border-left:6px solid #f2b233; }
.status-alert { background:#fff0f2; color:#a51d35; border-left:6px solid #e65068; }
.notice { padding: 14px 16px; border-radius: 14px; background: #f0f4ff; color: #394563; font-size: 14px; line-height: 1.55; }
.disclaimer { padding: 16px; border-radius: 16px; background: #fff4f6; border: 1px solid #ffd6df; color: #6e2638; font-size: 13px; line-height: 1.55; }
.ai-note { padding: 14px 16px; border-radius: 14px; background: #f4f0ff; border: 1px solid #e2d6ff; color: #3d2c66; font-size: 14px; line-height: 1.55; margin-top: 10px; }
div.stButton > button { border-radius: 14px; font-weight: 700; min-height: 46px; }
</style>
""", unsafe_allow_html=True)

# -------------------- Optional Groq (AI wellness note only — NOT used to detect vitals) --------------------
def get_ai_wellness_note(context: dict):
    """Returns a short, non-diagnostic note generated by Groq, or None if no API key is configured."""
    api_key = None
    try:
        api_key = st.secrets.get("GROQ_API_KEY")
    except Exception:
        pass
    if not api_key:
        import os
        api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return None
    try:
        from groq import Groq
        client = Groq(api_key=api_key)
        prompt = (
            "You are a cautious wellness assistant inside an educational app. "
            "Given this reading, write ONE short, friendly, non-diagnostic sentence "
            "(no medical diagnosis, no drug/dosage advice). Data: " + str(context)
        )
        resp = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=100,
            temperature=0.4,
        )
        return resp.choices[0].message.content.strip()
    except Exception:
        return None

def render_ai_note(context: dict):
    note = get_ai_wellness_note(context)
    if note:
        st.markdown(f'<div class="ai-note">🤖 <b>AI note:</b> {note}</div>', unsafe_allow_html=True)

def heart_status(bpm):
    if bpm < 50:
        return "🧊 Low", "status-watch", "Below the common adult resting range. This can be normal for trained people, but context matters."
    if bpm <= 100:
        return "💚 Typical", "status-good", "Within the common adult resting range."
    if bpm <= 120:
        return "🟡 Elevated", "status-watch", "Above the common adult resting range. Rest and repeat the measurement."
    return "🔴 High", "status-alert", "Higher than the common adult resting range. If you feel unwell, seek medical help."

def bp_status(sys, dia):
    if sys < 90 or dia < 60:
        return "🧊 Low", "status-watch", "Blood pressure is below the usual adult reference range."
    if sys < 120 and dia < 80:
        return "💚 Typical", "status-good", "Within the usual normal adult reference range."
    if sys < 130 and dia < 80:
        return "🟡 Elevated", "status-watch", "Systolic pressure is elevated."
    if sys < 140 or dia < 90:
        return "🟠 High", "status-watch", "Above the usual normal adult reference range."
    return "🔴 High", "status-alert", "This reading is high and should be discussed with a healthcare professional, especially if repeated."

def glucose_status(value, mode):
    if mode == "Fasting":
        if value < 70:
            return "🧊 Low", "status-watch", "Below the usual fasting reference range."
        if value < 100:
            return "💚 Typical", "status-good", "Within the usual fasting reference range."
        if value < 126:
            return "🟡 Elevated", "status-watch", "Above the usual fasting reference range."
        return "🔴 High", "status-alert", "High fasting glucose should be discussed with a healthcare professional."
    else:
        if value < 70:
            return "🧊 Low", "status-watch", "Below the usual reference range."
        if value < 140:
            return "💚 Typical", "status-good", "Within a common 2-hour post-meal reference range."
        if value < 200:
            return "🟡 Elevated", "status-watch", "Higher than the usual 2-hour post-meal reference range."
        return "🔴 High", "status-alert", "High glucose should be discussed with a healthcare professional."

# -------------------- Live camera pulse widget (pure browser JS — no Python video libs) --------------------
def render_pulse_widget():
    html = """
    <div style="font-family:'Inter',sans-serif; text-align:center; max-width:380px; margin:0 auto;">
      <div style="position:relative; width:100%;">
        <video id="video" autoplay playsinline muted style="width:100%; border-radius:18px; background:#111; display:block;"></video>
        <div id="roi" style="position:absolute; top:30%; left:35%; width:30%; height:40%; border:2px solid rgba(255,255,255,.85); border-radius:10px; pointer-events:none;"></div>
      </div>
      <canvas id="canvas" style="display:none;"></canvas>

      <div style="margin-top:10px;">
        <select id="facingSelect" style="padding:8px 10px; border-radius:10px; border:1px solid #ddd; font-size:13px;">
          <option value="user">🙂 Face (front camera)</option>
          <option value="environment">☝️ Fingertip (back camera + light)</option>
        </select>
      </div>

      <div id="status" style="margin:10px 0; font-weight:600; color:#394563; font-size:14px;">Tap Start, then hold steady for 15-20 seconds</div>

      <div style="display:flex; gap:10px; justify-content:center;">
        <button id="startBtn" style="flex:1; max-width:160px; padding:12px; border:none; border-radius:12px; background:#ff4f81; color:white; font-weight:700; font-size:14px;">🔴 Start</button>
        <button id="stopBtn" disabled style="flex:1; max-width:160px; padding:12px; border:none; border-radius:12px; background:#7c4dff; color:white; font-weight:700; font-size:14px; opacity:.5;">⏹ Stop &amp; Analyze</button>
      </div>

      <div id="result" style="margin-top:16px;"></div>
    </div>

    <script>
    (function(){
      let stream=null, recording=false, rafId=null, autoStopTimer=null;
      let samples=[];
      const videoEl=document.getElementById('video');
      const canvasEl=document.getElementById('canvas');
      const ctx=canvasEl.getContext('2d', {willReadFrequently:true});
      const startBtn=document.getElementById('startBtn');
      const stopBtn=document.getElementById('stopBtn');
      const statusEl=document.getElementById('status');
      const resultEl=document.getElementById('result');
      const facingSelect=document.getElementById('facingSelect');

      function setButtons(isRecording){
        startBtn.disabled=isRecording; startBtn.style.opacity=isRecording?'.5':'1';
        stopBtn.disabled=!isRecording; stopBtn.style.opacity=isRecording?'1':'.5';
      }

      async function start(){
        samples=[]; resultEl.innerHTML='';
        try{
          stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facingSelect.value}, audio:false});
          videoEl.srcObject=stream;
          await videoEl.play();
          recording=true; setButtons(true);
          statusEl.textContent='Recording... hold very still';
          loop();
          autoStopTimer=setTimeout(stop, 20000);
        }catch(e){
          statusEl.textContent='Camera access failed — please allow camera permission and use HTTPS.';
        }
      }

      function loop(){
        if(!recording) return;
        const w=videoEl.videoWidth, h=videoEl.videoHeight;
        if(w && h){
          canvasEl.width=w; canvasEl.height=h;
          ctx.drawImage(videoEl,0,0,w,h);
          const x=Math.floor(w*0.35), y=Math.floor(h*0.30), rw=Math.floor(w*0.30), rh=Math.floor(h*0.40);
          const frame=ctx.getImageData(x,y,rw,rh).data;
          let sum=0, n=0;
          for(let i=0;i<frame.length;i+=4){ sum+=frame[i+1]; n++; }
          samples.push({t: performance.now()/1000, v: sum/n});
        }
        rafId=requestAnimationFrame(loop);
      }

      function stop(){
        if(!recording) return;
        recording=false; setButtons(false);
        clearTimeout(autoStopTimer);
        cancelAnimationFrame(rafId);
        if(stream){ stream.getTracks().forEach(t=>t.stop()); }
        statusEl.textContent='Analyzing...';
        setTimeout(analyze, 50);
      }

      function interp(t, ts, vs){
        if(t<=ts[0]) return vs[0];
        if(t>=ts[ts.length-1]) return vs[vs.length-1];
        let lo=0, hi=ts.length-1;
        while(hi-lo>1){ const mid=(lo+hi)>>1; if(ts[mid]<t) lo=mid; else hi=mid; }
        const frac=(t-ts[lo])/((ts[hi]-ts[lo])||1);
        return vs[lo]+(vs[hi]-vs[lo])*frac;
      }

      function movingAvg(arr, win){
        const out=new Array(arr.length); const half=Math.floor(win/2);
        for(let i=0;i<arr.length;i++){
          const s=Math.max(0,i-half), e=Math.min(arr.length-1,i+half);
          let sum=0, c=0;
          for(let j=s;j<=e;j++){ sum+=arr[j]; c++; }
          out[i]=sum/c;
        }
        return out;
      }

      function fail(msg){
        resultEl.innerHTML='<div style="background:#fff0f2; color:#a51d35; border-left:5px solid #e65068; border-radius:12px; padding:12px 14px; font-size:14px; text-align:left;">⚠️ '+msg+'</div>';
        statusEl.textContent='Tap Start to try again';
      }

      function analyze(){
        if(samples.length<40) return fail('Not enough data captured. Try again and hold steadier.');
        const t0=samples[0].t, tN=samples[samples.length-1].t;
        const duration=tN-t0;
        if(duration<8) return fail('Recording too short — hold for at least 8-10 seconds.');

        const fs=30;
        const nPts=Math.floor(duration*fs);
        const ts=samples.map(s=>s.t), vs=samples.map(s=>s.v);
        const uniform=[];
        for(let i=0;i<nPts;i++){ uniform.push(interp(t0+i/fs, ts, vs)); }

        let sig=movingAvg(uniform,5);
        const longWin=Math.max(3, Math.round(fs*1.2));
        const baseline=movingAvg(sig, longWin);
        sig=sig.map((v,i)=>v-baseline[i]);

        const std=Math.sqrt(sig.reduce((a,b)=>a+b*b,0)/sig.length);
        if(std<0.02) return fail('Pulse signal too weak. Improve lighting and hold steady.');
        const thresh=std*0.4;
        const minDist=Math.floor(fs*60/190);
        const peaks=[]; let lastPeak=-minDist;
        for(let i=1;i<sig.length-1;i++){
          if(sig[i]>thresh && sig[i]>=sig[i-1] && sig[i]>=sig[i+1] && (i-lastPeak)>=minDist){
            peaks.push(i); lastPeak=i;
          }
        }
        if(peaks.length<5) return fail('Pulse signal too weak. Improve lighting and hold steady, then try again.');

        const intervals=[];
        for(let i=1;i<peaks.length;i++){
          const dt=(peaks[i]-peaks[i-1])/fs;
          if(dt>60/190 && dt<60/40) intervals.push(dt);
        }
        if(intervals.length<4) return fail('Could not find a stable pulse pattern. Try again.');

        const bpms=intervals.map(dt=>60/dt).sort((a,b)=>a-b);
        const median=bpms[Math.floor(bpms.length/2)];
        const mean=bpms.reduce((a,b)=>a+b,0)/bpms.length;
        const bstd=Math.sqrt(bpms.reduce((a,b)=>a+(b-mean)*(b-mean),0)/bpms.length);
        const cv=bstd/Math.max(mean,1);
        const consistency=Math.max(0,Math.min(1,1-cv));
        const durScore=Math.max(0,Math.min(1,duration/20));
        const quality=Math.round(100*(0.65*consistency+0.35*durScore));

        if(median<40 || median>190) return fail('Result outside the reliable range — please try again.');

        let status='💚 Typical', color='#087443';
        if(median<50){ status='🧊 Low'; color='#9a6500'; }
        else if(median<=100){ status='💚 Typical'; color='#087443'; }
        else if(median<=120){ status='🟡 Elevated'; color='#9a6500'; }
        else { status='🔴 High'; color='#a51d35'; }

        resultEl.innerHTML = '<div style="display:flex; gap:10px; justify-content:center; flex-wrap:wrap;">' +
          '<div style="background:white; border-radius:16px; padding:14px 18px; box-shadow:0 6px 20px rgba(0,0,0,.08); min-width:90px;">' +
            '<div style="font-size:26px; font-weight:800;">💓 '+median.toFixed(0)+'</div>' +
            '<div style="color:#687086; font-size:12px;">Estimated BPM</div></div>' +
          '<div style="background:white; border-radius:16px; padding:14px 18px; box-shadow:0 6px 20px rgba(0,0,0,.08); min-width:90px;">' +
            '<div style="font-size:26px; font-weight:800;">📈 '+quality+'%</div>' +
            '<div style="color:#687086; font-size:12px;">Signal quality</div></div>' +
          '<div style="background:white; border-radius:16px; padding:14px 18px; box-shadow:0 6px 20px rgba(0,0,0,.08); min-width:90px;">' +
            '<div style="font-size:18px; font-weight:800; color:'+color+';">'+status+'</div>' +
            '<div style="color:#687086; font-size:12px;">Interpretation</div></div>' +
        '</div>';
        statusEl.textContent='Done — tap Start to measure again';
      }

      startBtn.addEventListener('click', start);
      stopBtn.addEventListener('click', stop);
    })();
    </script>
    """
    components.html(html, height=560, scrolling=True)

# -------------------- Header --------------------
st.markdown("""
<div class="hero">
    <h1>💗 PulseCare AI</h1>
    <p>Mobile-friendly wellness dashboard • Live camera heart rate • Blood pressure • Blood glucose</p>
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class="disclaimer">
<b>Important:</b> This is an educational wellness app, not a medical device, and it cannot diagnose
heart disease, hypertension, diabetes, or any other condition. A phone camera can estimate <b>heart rate</b>
only. It <b>cannot</b> directly measure blood pressure or blood glucose — those need a real cuff/monitor or
glucose meter, entered manually below. For urgent symptoms, contact local emergency/medical services.
</div>
""", unsafe_allow_html=True)

# -------------------- Sidebar --------------------
with st.sidebar:
    st.header("🧭 Dashboard")
    page = st.radio("Choose a tool", ["💗 Heart Rate", "🩺 Blood Pressure", "🩸 Blood Glucose", "📊 Health Summary"])
    st.divider()
    st.caption("PulseCare AI • Experimental wellness project")
    st.caption("General educational ranges — not personalized medical advice.")

# -------------------- Heart Rate (LIVE, mobile camera) --------------------
if page == "💗 Heart Rate":
    st.subheader("💗 Live Camera Pulse Estimator")
    st.markdown("""
    <div class="notice">
    Choose face or fingertip mode below, tap <b>Start</b>, allow camera access, hold still for
    <b>15-20 seconds</b> under good, even light, then tap <b>Stop &amp; Analyze</b>. The camera, timing,
    and pulse calculation all run in your browser — nothing is uploaded.
    </div>
    """, unsafe_allow_html=True)

    render_pulse_widget()
    render_ai_note({"type": "heart_rate", "note": "user just completed a live camera pulse check"})

    st.divider()
    st.subheader("📌 Better measurement tips")
    for t in [
        "Keep the phone/camera steady and avoid moving.",
        "Use good, even lighting (or your flashlight for fingertip mode).",
        "Record for 15-20 seconds for a stable reading.",
        "Do not use the result for emergency decisions.",
        "Compare repeated readings only under similar resting conditions.",
    ]:
        st.write("• " + t)

# -------------------- Blood Pressure --------------------
elif page == "🩺 Blood Pressure":
    st.subheader("🩺 Blood Pressure Check")
    st.markdown("""
    <div class="notice">
    A smartphone camera cannot reliably measure blood pressure — it needs an actual cuff/monitor.
    Enter your reading below for an educational interpretation.
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        systolic = st.number_input("Systolic (upper) mmHg", min_value=50, max_value=250, value=120, step=1)
    with col2:
        diastolic = st.number_input("Diastolic (lower) mmHg", min_value=30, max_value=160, value=80, step=1)

    if st.button("🩺 Check Blood Pressure", use_container_width=True):
        status, css, explanation = bp_status(systolic, diastolic)
        st.markdown(f"""
        <div class="card {css}">
            <h2 style="margin-top:0">🩺 {systolic:.0f}/{diastolic:.0f} mmHg</h2>
            <b>{status}</b><br>{explanation}
        </div>
        """, unsafe_allow_html=True)
        render_ai_note({"type": "blood_pressure", "systolic": systolic, "diastolic": diastolic, "status": status})

    st.info("If a reading is repeatedly unusual, discuss it with a qualified healthcare professional.")

# -------------------- Blood Glucose --------------------
elif page == "🩸 Blood Glucose":
    st.subheader("🩸 Blood Glucose Check")
    st.markdown("""
    <div class="notice">
    A smartphone cannot directly measure blood glucose. Enter a reading from a glucose meter/approved
    sensor for an educational interpretation.
    </div>
    """, unsafe_allow_html=True)

    mode = st.selectbox("Reading type", ["Fasting", "2-hour post-meal"])
    unit = st.radio("Unit", ["mg/dL", "mmol/L"], horizontal=True)

    if unit == "mg/dL":
        value = st.number_input("Glucose value", min_value=20.0, max_value=700.0, value=90.0, step=1.0)
        mgdl = value
    else:
        value = st.number_input("Glucose value", min_value=1.0, max_value=40.0, value=5.0, step=0.1)
        mgdl = value * 18.0182

    if st.button("🩸 Check Glucose", use_container_width=True):
        status, css, explanation = glucose_status(mgdl, mode)
        st.markdown(f"""
        <div class="card {css}">
            <h2 style="margin-top:0">🩸 {value:.1f} {unit}</h2>
            <b>{status}</b><br>{explanation}
        </div>
        """, unsafe_allow_html=True)
        render_ai_note({"type": "glucose", "value": value, "unit": unit, "mode": mode, "status": status})

    st.info("Glucose targets can vary by person and medical situation. Use your clinician's targets when available.")

# -------------------- Summary --------------------
else:
    st.subheader("📊 Health Summary")
    st.markdown("""
    <div class="card">
        <h3>✨ Your wellness snapshot</h3>
        <p>PulseCare AI separates what a phone camera can genuinely estimate (heart rate) from readings
        that require real medical devices (blood pressure, glucose).</p>
    </div>
    """, unsafe_allow_html=True)

    st.write("### 🧠 What each feature can actually measure")
    for icon, feature, note in [
        ("💗 Heart rate", "Live camera estimate (face or fingertip)", "Experimental, not medical-grade"),
        ("🩺 Blood pressure", "Reading entered from a BP cuff/monitor", "Phone alone cannot measure this"),
        ("🩸 Blood glucose", "Reading entered from a glucose meter/sensor", "Phone alone cannot measure this"),
    ]:
        st.markdown(f'<div class="card"><h4>{icon} {feature}</h4><p>{note}</p></div>', unsafe_allow_html=True)

st.divider()
st.caption("💗 PulseCare AI is for educational wellness use only. It does not replace professional medical advice or validated medical devices.")
